### ISSUE TITLE
Installation question

### ISSUE THREAD

**Issue by Jarmir30** [animgoeth/ARA-CNN#1]
I tried to follow the installation process, but it's very hard for me to follow it. 
First of all, after clone a github repo, git clone https://github.com/animgoeth/ARA-CNN.git, I couldn't proceed "cd pathology-bayesian-cnn". Instead, I went to "ARA-CNN". 
Second, could you please inform me where the simple_cnn.py is located?
I tried to run the code using "python src/simple_cnn.py --output-path /your/output/path --dataset-path /your/dataset/path" couldn't see the simple_cnn,py file.

**Comment by animgoeth** [comment]
Thank you for pointing that out. The installation instructions have been updated with the correct paths.
