### ISSUE TITLE
There's a small issue

### ISSUE THREAD

**Issue by slee172** [animgoeth/ARA-CNN#2]
Dear,

I tried to run it again python src/ara_cnn.py --output-path myoutput/ --dataset-path dataset/
But, got an error,
AttributeError: 'Namespace' object has no attribute 'datasets_path'

It seems like your code has no parameter named datasets_path.

I found that "args.datasets_path" in your main code, but you set it to "dataset_path".

Could you please update your code so that I could run it again.

I think that your work is very good and I'd like to test it.

**Comment by animgoeth** [comment]
Thanks a lot for testing the code and finding that bug. It's fixed now, so please try to run it again.

I'm closing this issue - if you notice any other problems, please report a new one.
