### ISSUE TITLE
Source code to find the ROC and Precision Recall Curve

### ISSUE THREAD

**Issue by AshishRMenon** [animgoeth/ARA-CNN#9]
Can you kindly mention the procedure you used to find the ROC curve and Precision Recall Curve

**Comment by marmarmarmar** [comment]
These metrics were computed based on the output of model evaluation scripts - which provided scores for appropriate images. We used [this](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.roc_auc_score.html?highlight=roc#sklearn.metrics.roc_auc_score) for `ROC_AUC` score and [this](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.average_precision_score.html#sklearn.metrics.average_precision_score) for `average-precision`.
